// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sofer.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_CREATE    Message_Type = 0
	Message_JOIN      Message_Type = 1
	Message_MULTICAST Message_Type = 2
	Message_LEAVE     Message_Type = 3
)

var Message_Type_name = map[int32]string{
	0: "CREATE",
	1: "JOIN",
	2: "MULTICAST",
	3: "LEAVE",
}

var Message_Type_value = map[string]int32{
	"CREATE":    0,
	"JOIN":      1,
	"MULTICAST": 2,
	"LEAVE":     3,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9120030e5ac04b9, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Message_Type" json:"type,omitempty"`
	Group                []byte       `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9120030e5ac04b9, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_CREATE
}

func (m *Message) GetGroup() []byte {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("sofer.proto", fileDescriptor_f9120030e5ac04b9) }

var fileDescriptor_f9120030e5ac04b9 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xce, 0x4f, 0x4b,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x9a, 0xc8, 0xc8, 0xc5,
	0xee, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xa4, 0xc2, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa0, 0x57, 0x90, 0xa4, 0x07, 0x95, 0xd2, 0x0b, 0xa9,
	0x2c, 0x48, 0x0d, 0x02, 0xcb, 0x0a, 0x89, 0x70, 0xb1, 0xa6, 0x17, 0xe5, 0x97, 0x16, 0x48, 0x30,
	0x29, 0x30, 0x6a, 0xf0, 0x04, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12,
	0xcc, 0x60, 0x41, 0x30, 0x5b, 0xc9, 0x8c, 0x8b, 0x05, 0xa4, 0x4f, 0x88, 0x8b, 0x8b, 0xcd, 0x39,
	0xc8, 0xd5, 0x31, 0xc4, 0x55, 0x80, 0x41, 0x88, 0x83, 0x8b, 0xc5, 0xcb, 0xdf, 0xd3, 0x4f, 0x80,
	0x51, 0x88, 0x97, 0x8b, 0xd3, 0x37, 0xd4, 0x27, 0xc4, 0xd3, 0xd9, 0x31, 0x38, 0x44, 0x80, 0x49,
	0x88, 0x93, 0x8b, 0xd5, 0xc7, 0xd5, 0x31, 0xcc, 0x55, 0x80, 0x39, 0x89, 0x0d, 0xec, 0x3c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x04, 0x73, 0x1d, 0xad, 0x00, 0x00, 0x00,
}
